### ISSUE TITLE
Problem with leader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [braillespecs/obfl#31]
```
"The leader element moves the location of the following piece of text within 
the current row."

In the following example, the "following piece of text" appears to be the space 
(between leader and page-number).

   <leader position="100%" align="right" pattern="."/>
   <page-number ref-id="d3e2800"/>

The output is:

⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠼⠁

But what I would like to achieve is that both the space and the page number are 
kept on the same row, and both are aligned to the right:

⠄⠄⠄⠄⠄⠄⠄⠀⠼⠁

1. Is this a bug in Dotify?
2. Does OBFL need to be more specific about what exactly "text following the 
leader" is? I was assuming that it means *all* the following inline content. 
```

Original issue reported on code.google.com by `bertfrees` on 15 Oct 2014 at 11:31

**Comment by bertfrees** [comment]
See e.g. https://github.com/daisy/pipeline-mod-braille/blob/f672eb118f8a65988a8e719d86b43ed6902f6ba9/pipeline-braille-utils/dotify/dotify-formatter/src/test/xprocspec/test_obfl-to-pef.xprocspec#L206

**Comment by bertfrees** [comment]
See test [page-number-follows-leader](https://rawgit.com/snaekobbi/dotify/168c50fe265c9b007cf5557b95b0b1bf4fe44201/dotify.formatter.impl/test/org.daisy.dotify.engine.impl.resource-files.tests-overview.html#dp2/page-number-follows-leader-input.obfl)

**Comment by bertfrees** [comment]
See Dotify issue: https://github.com/joeha480/dotify/issues/120.
