### ISSUE TITLE
New OBFL feature for underlining a block of text

### ISSUE THREAD

**Issue by bertfrees** [braillespecs/obfl#50]
The underlining may not extend further than where the text begins and ends.

For example:

``` xml
<block align="center" ...>
  text
</block>
```

should become:

```
       text
       ----
```

and:

``` xml
<block ...>
  a longer block of text that does not fit on one line
</block>
```

should become:

```
a longer block of text that does
not fit on one line
--------------------------------
```

Because this behavior is only desired for simple blocks of text and not for nested blocks, we don't need to change the model of blocks, i.e. the width of a block can remain to be equal to the width of the parent block (or the page) minus any left/right margins, padding and borders. It is only the properties of bottom (and top?) borders that need to be configurable, or, if we wish to not touch borders, come up with a new kind of underlining that can be made in addition to a bottom border.

In what follows I choose the latter but the same can be applied to the former.

`block` would get new attributes called `text-underline-style`, `text-underline-width` and `text-underline-align` which would behave as described above when the block contains only text.

I'm not sure what should happen if the block contains other blocks. It is not important for the requirement, but the behavior should of course be defined properly. The behavior should probably be in line with `first-line-indent` regarding whether the property is inherited and how you determine what the first line is. However I don't know how first-line-indent behaves exactly.
- Either you just ignore the "text-underline" attributes in the case of nested blocks. This is probably the simplest solution.
- Or, if a block contains another block with a top or bottom border, you could say that the top and bottom borders of the containing block are always at least as wide as the inner block.
- What if a block contains another block that hasn't got a bottom border?
- What if a block contains both text and other blocks? I don't even know if mixed content is allowed in OBFL, because I never generate such OBFL in my css-to-obfl step.

**Comment by bertfrees** [comment]
- [ ] To do: update schema and documentation

**Comment by bertfrees** [comment]
This can be closed I think.

**Comment by joeha480** [comment]
Ok, closing
