### ISSUE TITLE
Allow toc-sequence within post-content

### ISSUE THREAD

**Issue by bertfrees** [braillespecs/obfl#55]
This is a requirement for Dedicon: see https://github.com/snaekobbi/pipeline-mod-dedicon/issues/40

Related: https://github.com/braillespecs/obfl/issues/23

**Comment by bertfrees** [comment]
This was very trivial to fix in Dotify. Now what is left is to change OBFL.

**Comment by joeha480** [comment]
@bertfrees Ok, I've merged this commit

**Comment by bertfrees** [comment]
- [ ] To do: update OBFL schema and documentation

**Comment by joeha480** [comment]
@bertfrees that's all that was left, right?

**Comment by bertfrees** [comment]
Yes.
