### ISSUE TITLE
Support wrapping of text around header/footer fields

### ISSUE THREAD

**Issue by bertfrees** [braillespecs/obfl#60]
In braille CSS I support this by looking at the top and bottom page margins and the page margin boxes (top-left, top-center, top-right, bottom-right, bottom-center, bottom-left) as two different things. The top/bottom margin height can be smaller than the height of the biggest top/bottom margin box, in which case that box extends into the page area, and the text in the page area can wrap around the margin box. See http://braillespecs.github.io/braille-css/#h4_page-margin-boxes.

Because in OBFL there is a strict hierarchy between header/footer and field, the same model can not be easily applied.

One idea is to add an attribute to field for specifying whether text can flow into it. A field with this attribute may of course not have any content.

**Comment by bertfrees** [comment]
I have a proposal with 3 variations.

1. The `field` element may be empty which means allowing text from the body to flow into it. How exactly text is flowed into it can be made up to the implementation, but as a general rule the combined area in the header/footer that is made up of the empty fields and that extends the page body should:
   - be rectangular
   - be connected with the page body
   - be less wide than the page
   - there may be at most one at the top and one at the bottom.
   
   By default, the distribution of the fields should be done as if the field contains an empty string, and the available space should be filled up afterwards. If a more advanced distribution is needed we can create new modes.

2. Instead of an empty `field` element you could allow a new dedicated placeholder element inside `footer` and `header`. I haven't found a good name yet. (`text-from-body`?)

3. As a possible extention to solution 2, the new element could optionally have the same content as `field`. How the element behaves then depends on the content. If it computes to whitespace-only text, it behaves like `field`, otherwise text is allowed to flow into it.

The problem with solution 1 is that I'm not sure it is backwards-compatible. It should be, because the specification says the [`field` element](http://braillespecs.github.io/obfl/obfl-specification.html#L665) must have content, but in practice I think empty fields are already allowed.

**Comment by bertfrees** [comment]
Joel's idea: variation 2 but name it `text-flow-area`.

**Comment by bertfrees** [comment]
In addition, Joel says the element could have a `width` attribute. However I don't need that at the moment, I just use all the space available.

**Comment by joeha480** [comment]
The variation with an attribute called allow-text-flow would be on a regular field-element:
- that is "false" by default
- that can only contain text from the body, if the attribute is set to "true" and the effective contents of the field is empty space, either because it doesn't contain any elements or because the child elements resolve to an empty string.

width could possibly be applied to all fields.

**Comment by bertfrees** [comment]
I've updated the spec.

**Comment by joeha480** [comment]
Ok, I've merged this.
