### ISSUE TITLE
Support end of volume notification

### ISSUE THREAD

**Issue by joeha480** [braillespecs/obfl#70]
Add support for end of volume notifications

**Comment by bertfrees** [comment]
@joeha480 We have this use case now at SBS (https://github.com/sbsdev/pipeline-mod-sbs/issues/68). There are two features that kind of do what we want, but not exactly. `post-content` can only contain sequences, not blocks, but we don't want the notification to start on a new page. Then there is the new `volume-transition` but with this you can not unconditionally add content to the end of the volume; there must be a break of a sequence or block.

**Comment by joeha480** [comment]
@bertfrees I think I prefer extending volume-transition, but note that in that case, the notification would be before post-content.

**Comment by bertfrees** [comment]
That would be a problem because in SBS's case the announcement should come after the post-content (end notes).

**Comment by joeha480** [comment]
After a short discussion with SBS, we agreed that extending volume-transition is the best option. This would add a new element to the volume-transition section.

**Comment by joeha480** [comment]
Closed in edb3c7a5cbe88d7cac84ff4759756498714afc5b
